### ISSUE TITLE
json字符串解析失败：json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by CYDXDianXian** [kushidou/bili-notice-hoshino#10]
貌似在新添加关注up时会出现，未看到插件的log中报错，只有在hoshinobot的log中记录下了报错，目前未见使用异常
```
[2022-06-30 16:53:55,251 b站动态监视器] ERROR: <class 'json.decoder.JSONDecodeError'> occured when doing scheduled job bili_watch.
[2022-06-30 16:53:55,251 b站动态监视器] ERROR: Expecting ',' delimiter: line 1 column 105 (char 104)
Traceback (most recent call last):
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\service.py", line 349, in wrapper
    ret = await func()
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 24, in bili_watch
    rst, dylist = await dymgr.get_update()
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 145, in get_update
    dynamic = drawCard.Card(card)
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 60, in __init__
    self.card=json.loads(card_content)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 105 (char 104)
```

**Comment by CYDXDianXian** [comment]
感谢老师修复问题，辛苦了！我更新后测试一段时间再来反馈！

**Comment by CYDXDianXian** [comment]
用了一天没什么问题了，感谢老师修复，issues我先关了
