### ISSUE TITLE
Windows环境下部署还是存在导入库问题

### ISSUE THREAD

**Issue by SanaChitose** [kushidou/bili-notice-hoshino#15]
系统版本：windows server 2012
python版本：3.8
错误代码：
[2022-08-08 15:03:39,084 nonebot] ERROR: Failed to import "hoshino.modules.bili-notice-hoshino.bili_notice_hoshino", err
or: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files\UniConvertor-2.0rc5\dlls\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1
[2022-08-08 15:03:39,084 nonebot] ERROR: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files\UniConvertor-2.0rc5\dlls\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nonebot\plugin.py", line 253,
 in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import
_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\bot\HoshinoBot\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 4, in <module>
    from . import dymgr
  File "C:\bot\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 5, in <module>
    from .res import drawCard
  File "C:\bot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 8, in <module>
    from .getImg import get_ico, get_Image, save_Image
  File "C:\bot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\getImg.py", line 8, in <module>
    import cairosvg as svg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cairosvg\__init__.py", line 2
6, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cairosvg\surface.py", line 9,
 in <module>
    import cairocffi as cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cairocffi\__init__.py", line
48, in <module>
    cairo = dlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cairocffi\__init__.py", line
45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files\UniConvertor-2.0rc5\dlls\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1
[2022-08-08 15:03:39,115 nonebot] ERROR: Failed to import "hoshino.modules.bili-notice-hoshino.dymgr", error: no library
 called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files\UniConvertor-2.0rc5\dlls\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1
[2022-08-08 15:03:39,115 nonebot] ERROR: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files\UniConvertor-2.0rc5\dlls\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nonebot\plugin.py", line 253,
 in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import
_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\bot\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 5, in <module>
    from .res import drawCard
  File "C:\bot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 8, in <module>
    from .getImg import get_ico, get_Image, save_Image
  File "C:\bot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\getImg.py", line 8, in <module>
    import cairosvg as svg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cairosvg\__init__.py", line 2
6, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cairosvg\surface.py", line 9,
 in <module>
    import cairocffi as cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cairocffi\__init__.py", line
48, in <module>
    cairo = dlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cairocffi\__init__.py", line
45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files\UniConvertor-2.0rc5\dlls\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1

**Comment by SanaChitose** [comment]
我已经详细阅读 #6 和 #8 ，并按照https://www.jianshu.com/p/5f566c26334f和https://github.com/kushidou/bili-notice-hoshino/wiki/%E9%83%A8%E7%BD%B2%E6%8F%92%E4%BB%B6中的提示操作。
![图片](https://user-images.githubusercontent.com/102790983/183360464-0ad75cd3-d883-4e91-bc44-8b30fa51670d.png)
![图片](https://user-images.githubusercontent.com/102790983/183360516-b70d3be9-8ddc-4f85-adea-06ac01565913.png)
![图片](https://user-images.githubusercontent.com/102790983/183360766-b7dfa164-cdff-4327-b869-11594be5040b.png)
uppers/list.json文件是我手动创建的，重启多次依然提示错误，核心错误代码
no library called "cairo" was found
cannot load library 'C:\Program Files\UniConvertor-2.0rc5\dlls\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1

**Comment by kushidou** [comment]
嗯，这个svg库引发了很多问题。我现在没有环境可以来模拟并修复你的问题，所以我计划从根本上解决掉它。

----- 

本来使用svg图像，一方面是从b站网页扒下来了这类型的文件直接用了，另一方面是预留以后的自定义元素尺寸的需求。
现在把svg直接转换成稍大的png图像保存，和调用，舍掉实时的类型转换了。

**Comment by SanaChitose** [comment]
> 

感谢回复！
我在查找资料尝试解决问题的过程中，安装过一个pycairo的第三方库，不知道对解决问题有没有思路上的帮助

**Comment by kushidou** [comment]
> > 
> 
> 感谢回复！ 我在查找资料尝试解决问题的过程中，安装过一个pycairo的第三方库，不知道对解决问题有没有思路上的帮助

与第三方库的版本、路径可能都有关系。这个SVG库我也不熟悉，属于是需要了才找来的，它所包含的诸多隐患我也没有做前期调研，最终决定还是抛弃这个库比较方便。之后再考虑svg转换的问题。

**Comment by SanaChitose** [comment]
经过测试 安装requirements.txt中的插件以及pycairo以后已经
可以成功运行
![图片](https://user-images.githubusercontent.com/102790983/184792455-4d9b13bd-dfe8-480b-832b-c03d78e33824.png)
![图片](https://user-images.githubusercontent.com/102790983/184792437-c1b98fe9-0582-4f60-8bfb-1e43cb27b2b0.png)

**Comment by SanaChitose** [comment]
> 经过测试 安装requirements.txt中的插件以及pycairo以后已经 可以成功运行 ![图片](https://user-images.githubusercontent.com/102790983/184792455-4d9b13bd-dfe8-480b-832b-c03d78e33824.png) ![图片](https://user-images.githubusercontent.com/102790983/184792437-c1b98fe9-0582-4f60-8bfb-1e43cb27b2b0.png)

补充一下 需要uninstall cairosvg这个库
