### ISSUE TITLE
bili_watch运行报错

### ISSUE THREAD

**Issue by SonderXiaoming** [kushidou/bili-notice-hoshino#20]
[2022-09-11 09:49:11,045 b站动态监视器] ERROR: <class 'ValueError'> occured when doing scheduled job bili_watch.
[2022-09-11 09:49:11,045 b站动态监视器] ERROR: invalid literal for int() with base 10: '1     # 0=不更新，1=从gitee检查更新(国内推荐)，2=从github检查更新'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\service.py", line 349, in wrapper
    ret = await func()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 53, in bili_watch
    rst, dylist = await dymgr.get_update()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 155, in get_update
    await check_plugin_update()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 720, in check_plugin_update
    way = conf.getint('common','if_check_update')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: '1     # 0=不更新，1=从gitee检查更新(国内推荐)，2=从github检查更新'

**Comment by SonderXiaoming** [comment]
重拉配置文件好了，没事了
