### ISSUE TITLE
一个解码报错和一个keyError的bug

### ISSUE THREAD

**Issue by MSCMonster** [kushidou/bili-notice-hoshino#21]
以下是Hoshino的日志

[2022-11-27 05:22:54,003 b站动态订阅] INFO: Scheduled job bili_watch start.
[Debug] Start getting ID=397985349
[2022-11-27 05:22:54,003] INFO in service: Scheduled job bili_watch start.
Error while decode card data json
[2022-11-27 05:22:54,140 b站动态订阅] ERROR: <class 'UnicodeEncodeError'> occured when doing scheduled job bili_watch.
[2022-11-27 05:22:54,140] ERROR in service: <class 'UnicodeEncodeError'> occured when doing scheduled job bili_watch.
[2022-11-27 05:22:54,140 b站动态订阅] ERROR: 'gbk' codec can't encode character '\U0001f3b6' in position 245: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\bot\QQBot\HoshinoBot\hoshino\modules\bili-notice\res\drawCard.py", line 45, in __init__
    self.card["origin"] = json.loads(self.card["origin"])
KeyError: 'origin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\bot\QQBot\HoshinoBot\hoshino\service.py", line 344, in wrapper
    ret = await func()
  File "C:\Users\Admin\Desktop\bot\QQBot\HoshinoBot\hoshino\modules\bili-notice\bili_notice_hoshino.py", line 65, in bili_watch
    rst, dylist = await dymgr.get_update()
  File "C:\Users\Admin\Desktop\bot\QQBot\HoshinoBot\hoshino\modules\bili-notice\dymgr.py", line 198, in get_update
    dynamic = drawCard.Card(card)
  File "C:\Users\Admin\Desktop\bot\QQBot\HoshinoBot\hoshino\modules\bili-notice\res\drawCard.py", line 57, in __init__
    json.dump(dylist, f, ensure_ascii=False)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f3b6' in position 245: illegal multibyte sequence
[2022-11-27 05:22:54,140] ERROR in service: 'gbk' codec can't encode character '\U0001f3b6' in position 245: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\bot\QQBot\HoshinoBot\hoshino\modules\bili-notice\res\drawCard.py", line 45, in __init__
    self.card["origin"] = json.loads(self.card["origin"])
KeyError: 'origin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\bot\QQBot\HoshinoBot\hoshino\service.py", line 344, in wrapper
    ret = await func()
  File "C:\Users\Admin\Desktop\bot\QQBot\HoshinoBot\hoshino\modules\bili-notice\bili_notice_hoshino.py", line 65, in bili_watch
    rst, dylist = await dymgr.get_update()
  File "C:\Users\Admin\Desktop\bot\QQBot\HoshinoBot\hoshino\modules\bili-notice\dymgr.py", line 198, in get_update
    dynamic = drawCard.Card(card)
  File "C:\Users\Admin\Desktop\bot\QQBot\HoshinoBot\hoshino\modules\bili-notice\res\drawCard.py", line 57, in __init__
    json.dump(dylist, f, ensure_ascii=False)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f3b6' in position 245: illegal multibyte sequence

**Comment by kushidou** [comment]
看起来是unicode和gbk编码问题，能找到出错的动态的id吗，我尝试复现一下
