### ISSUE TITLE
怎么改了不更新，这里面还是一直跳这个提示

### ISSUE THREAD

**Issue by 1055169799** [kushidou/bili-notice-hoshino#22]
[2022-12-30 18:02:07,813 b站动态监视器] ERROR: <class 'ValueError'> occured when doing scheduled job bili_watch.
[2022-12-30 18:02:07,813 b站动态监视器] ERROR: invalid literal for int() with base 10: '0     # 0=不更新，1=从gitee检查更新(国内推荐)，2=从github检查更新'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\service.py", line 345, in wrapper
    ret = await func()
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 53, in bili_watch
    rst, dylist = await dymgr.get_update()
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\dymgr.py", line 155, in get_update
    await check_plugin_update()
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\dymgr.py", line 732, in check_plugin_update
    way = conf.getint('common','if_check_update')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: '0     # 0=不更新，1=从gitee检查更新(国内推荐)，2=从github检查更新'

**Comment by 1055169799** [comment]
> 抱歉前几天都没打开邮箱和github，没有看到你的问题。
> 
> 看起来可能是配置文件注释的问题，尝试**把#号以及后面的注释删除或者移动到新行**。之前已经移除了这个隐患，您也可以更新到最新版，并且重新配置一下config.ini文件
> 
> 如果方便的话，可以把`config.ini`文件的`if_check_update =   ` 字段贴出来，看一下是否有其他的可能原因。

好的，我后面有机会再试试吧，我服务器到期了，后面换一个服务器才能再试了。

**Comment by 1055169799** [comment]
我重新下载了整个插件覆盖进去
打开之后就是这样的
![image](https://user-images.githubusercontent.com/41286675/210725504-ef57b030-5f53-4137-a412-caa2726d5418.png)

这个是运行窗口的显示

`[2023-01-05 15:27:00,059 b站动态监视器] INFO: Scheduled job bili_watch start.
2023-01-05 15:27:00.060 | INFO     | hoshino.modules.bili-notice-hoshino.dymgr:clean_cache:696 - Clean image cache finish!
2023-01-05 15:27:00.063 | INFO     | hoshino.modules.bili-notice-hoshino.dymgr:clean_cache:721 - Clean uppers history finish!
[2023-01-05 15:27:00,065 b站动态监视器] ERROR: <class 'ValueError'> occured when doing scheduled job bili_watch.
[2023-01-05 15:27:00,065 b站动态监视器] ERROR: invalid literal for int() with base 10: '0     # 0=不更新，1=从gitee检查更新(国内推荐)，2=从github检查更新'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\service.py", line 345, in wrapper
    ret = await func()
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 53, in bili_watch
    rst, dylist = await dymgr.get_update()
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\dymgr.py", line 155, in get_update
    await check_plugin_update()
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\dymgr.py", line 732, in check_plugin_update
    way = conf.getint('common','if_check_update')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: '0     # 0=不更新，1=从gitee检查更新(国内推荐)，2=从github检查更新'
`

然后这个是 config.ini 内的所有内容

`# b站动态监视器配置文件。请不要任何删除配置项。
# 内容请参看https://github.com/kushidou/bili-notice-hoshino/wiki/config%E9%85%8D%E7%BD%AE
[common]
# 轮询间隔，单位秒，不建议低于5s
poll_time = 15
log_max_days = 7
# trace, debug, info, warn, error
log_level = debug
# 分钟，如果动态时间长于这个，认为是旧动态并忽略
available_time = 30
# 只推送视频内容
only_video = false
# 只推送动态内容, only_video=ture时失效
only_dynamic = false
# 是否推送转发内容，上面两个任意为true时失效
repost = true
# 全局屏蔽词，如果想看广告的话这里留空
global_black_words = 拼多多,恰饭,课程,免费领取
# 默认是否显示转发的抽奖动态，true或false
sharelucky = false       # 是否发布 转发的 抽奖动态（含转发他人抽奖、发布抽奖结果）
# 是否检查更新，如果有更新也只会输出在日志中
if_check_update = 0     # 0=不更新，1=从gitee检查更新(国内推荐)，2=从github检查更新

# 图片及缓存
[cache]
# 素材图片缓存时间（包括图文动态、视频封面、专栏封面等。）0=不删除
image_cache_days = 7
# 是否缓存生成的动态卡片，命名方式： uid_nick_dyid_type.png
dycard_cache = false
# 动态卡片缓存时间，0=不删除
dycard_cache_days = 7

[authority]
# 关注和取关指令的执行权限
# admin = 只有机器人管理员可以, group = 只有admin+群主+群管理, all = 所有人都可以
follow = group
# 机器人控制指令，注意指令是全局生效的，建议使用admin。
cmd = admin

# 卡片绘制相关
[drawCard]
# 卡片风格，支持web和app
style = web
# 动态卡片宽度，默认680
width = 680 
# 动态卡片最大长度，未使用
height_max = 1200
# 元素缩放倍率，以680为基础。过小可能比例不协调，过大可能元素超出图片。
box_size_agnification = 1.0
# 图片的限制尺寸，作为长边，**min_size是多图时图片的正方形裁剪大小**
image_max_size = 320
image_min_size = 104 
# 单图时，图片的最大比例，纵图和横图共享，默认3:4，填入整数。也可以16:9等来适配手机图片。
image_ratio = 3:4

# 大字体，用户昵称
# large font, nickname
font_size_1 = 18
# 中字体，正文、视频(等)标题、转发页的昵称
# medium font size, normal text, title of video/article/audio/..., nickname in repost
font_size_2 = 14
# 小字体，三连信息、视频(等)简介、视频(等)播放和弹幕信息
# small font size, like/comment/repost number, description and play count of video/article/audio/...
font_size_3 = 12
# 是否显示用户的头像框
need_avatar = true
# 是否显示用户的卡片背景牌
need_fan_bg = true
`

**Comment by kushidou** [comment]
删除更新检查那一行#号及后面的内容，或者使用`git  clone`的方式获取最新代码（而不是从release下载）

**Comment by 1055169799** [comment]
> 删除更新检查那一行#号及后面的内容，或者使用`git  clone`的方式获取最新代码（而不是从release下载）

行，我试试Git
