### ISSUE TITLE
uid关注报错

### ISSUE THREAD

**Issue by yangzhan-1** [kushidou/bili-notice-hoshino#24]
[2023-04-23 10:09:04,502 b站动态监视器] ERROR: <class 'json.decoder.JSONDecodeError'> occured when bili_add handling message -132771600.
[2023-04-23 10:09:04,504 b站动态监视器] ERROR: Extra data: line 1 column 47 (char 46)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot-master\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot-master\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 122, in bili_add

    rst, res = dymgr.follow(str(uid), ev.group_id)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot-master\hoshino\modules\bili-notice-hoshino\dymgr.py", line 351, in follow
    resj = json.loads(res.text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 47 (char 46)

**Comment by yangzhan-1** [comment]
名字关注也找不到

**Comment by yangzhan-1** [comment]
要先at机器人再写关注name才能找到文档有歧义啊

**Comment by kushidou** [comment]
麻烦提供一下关注的up主昵称或id，或者发送的关注消息。最近b站api访问请求比较严格，请求失败后返回的内容也经常在变，有些error需要等详细的分析出来了才会进行修改
关于“歧义”这部分，可以详细描述一下吗？是指 "关注xxx@bot"这样的写法吗？

**Comment by yangzhan-1** [comment]
关注name@机器人这样就搜索不到，@机器人关注name这样就可以

**Comment by yangzhan-1** [comment]
uid：397362792

**Comment by yangzhan-1** [comment]
我刚刚试着发了测试的动态，2分钟了还没监控到发送到群里，这延迟是不是太高了

**Comment by kushidou** [comment]
> 关注name@机器人这样就搜索不到，@机器人关注name这样就可以

提取关键词是使用的hoshino的API，这个问题我之后观察一下，如果可能的话下个版本修复。



> 我刚刚试着发了测试的动态，2分钟了还没监控到发送到群里，这延迟是不是太高了

延迟与轮询间隔、关注up主数量直接相关。如果你关注的不多且长期没有收到消息，可能是下面几个情况：
1. 轮询被卡住了，尝试重启机器人，并查看启动和运行过程中有没有出现错误信息
2. CDN问题，b站使用了缓存功能，导致你的服务器获取到的信息是来自数分钟前的而不是最新的。
3. 网络问题。可能你的ip被b站ban了，尝试用浏览器访问、登录一下b站，然后过几分钟在尝试使用机器人获取信息。

**Comment by kushidou** [comment]
昨天群友也报告了类似的问题，关注的时候，b站服务器拒绝了连接，并返回了两段json，导致插件解析失败（python内置的json只能解析一段json），如图：
![image](https://user-images.githubusercontent.com/26197294/233816855-4aa1bd8d-1b53-43d0-a66c-639e8285fe6b.png)


暂时不能确定问题发生的原因以及涉及的API，需要更多的证据才能确定解决方案。你可以尝试按照`uppers_exapmle/list.json`里面的格式暂时手动添加关注者，然后任意群里发送`bili-ctl  reload `进行手动重载。

我会尽快处理这个问题。
