### ISSUE TITLE
启动出现报错TypeError: call_action() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by JokerHex** [kushidou/bili-notice-hoshino#29]
报错log为：

```[2023-08-30 16:39:02,982 nonebot] ERROR: Failed to import "hoshino.modules.bili-notice-hoshino.bili_notice_hoshino", error: call_action() takes 2 positional arguments but 3 were given
[2023-08-30 16:39:02,982 nonebot] ERROR: call_action() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\hoshino\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\ProgramData\Anaconda3\envs\hoshino\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 64, in <module>
    async def startup():
TypeError: call_action() takes 2 positional arguments but 3 were given```

用的版本是新上的0.b.8.4，依赖也都装过了，换回发行版没出现问题。
请大佬帮忙看看。

**Comment by kushidou** [comment]
把 bili_notice_hoshino.py  的第63-65行注释掉或者删掉。可能与python版本有关。

**Comment by JokerHex** [comment]
> 把 bili_notice_hoshino.py 的第63-65行注释掉或者删掉。可能与python版本有关。

注释掉之后解决了，python版本是3.8.13
