### ISSUE TITLE
正常使用几天后报错UnicodeEncodeError: 'gbk' codec can't encode character '\u200b' in position 256: illegal multibyte sequence

### ISSUE THREAD

**Issue by FanJZSS** [kushidou/bili-notice-hoshino#36]
```
[2024-02-02 23:30:13,179 b站动态监视器] ERROR: <class 'UnicodeEncodeError'> occured when doing scheduled job bili_watch.
[2024-02-02 23:30:13,179 b站动态监视器] ERROR: 'gbk' codec can't encode character '\u200b' in position 256: illegal multibyte sequence
Traceback (most recent call last):
  File "D:\QQ-Bot\HoshinoBot_Blue\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 45, in __init__
    self.card["origin"] = json.loads(self.card["origin"])
KeyError: 'origin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\QQ-Bot\HoshinoBot_Blue\hoshino\service.py", line 350, in wrapper
    ret = await func()
  File "D:\QQ-Bot\HoshinoBot_Blue\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 72, in bili_watch
    rst, dylist = await dymgr.get_update()
  File "D:\QQ-Bot\HoshinoBot_Blue\hoshino\modules\bili-notice-hoshino\dymgr.py", line 303, in get_update
    dynamic = drawCard.Card(card)
  File "D:\QQ-Bot\HoshinoBot_Blue\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 57, in __init__
    json.dump(dylist, f, ensure_ascii=False)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
UnicodeEncodeError: 'gbk' codec can't encode character '\u200b' in position 256: illegal multibyte sequence

```
感觉是关注的动态有特殊字符的问题？

**Comment by kushidou** [comment]
初步看起来是json采用系统默认的GBK解码出现问题，实际上应该使用utf-8。检查了一遍代码，这是唯一一个没有指定utf-8的地方
![image](https://github.com/kushidou/bili-notice-hoshino/assets/26197294/f42564fc-7695-417e-9ccf-03c1a10fdc9c)

**Comment by FanJZSS** [comment]
> 初步看起来是json采用系统默认的GBK解码出现问题，实际上应该使用utf-8。检查了一遍代码，这是唯一一个没有指定utf-8的地方 ![image](https://private-user-images.githubusercontent.com/26197294/302088473-f42564fc-7695-417e-9ccf-03c1a10fdc9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDc5NTgsIm5iZiI6MTcwNzA0NzY1OCwicGF0aCI6Ii8yNjE5NzI5NC8zMDIwODg0NzMtZjQyNTY0ZmMtNzY5NS00MTdlLTljY2YtMDNjMWExMGZkYzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDExNTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZDEyYTE5OWYyMTZjZDA4NjM1NTI5MWRhMWZjMDFhN2EwZTdmMDZiZTE5ZjJmNzQyNWJiZjA1MTA5ZTYzMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MAOwD_cHP-Wq9cGXzhxG8beQRbI9FqS8zV8wwjK4D0U)

`drawCard.py`第58行少了个`, `
![0](https://github.com/kushidou/bili-notice-hoshino/assets/96369018/686066f9-1b74-4a90-aaff-202e861d39e8)

**Comment by kushidou** [comment]
6，忙中出错了
