### ISSUE TITLE
出现报错ERROR: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by FanJZSS** [kushidou/bili-notice-hoshino#38]
今天出现的报错，之前无问题

```
[2024-03-19 16:38:08,198 b站动态监视器] ERROR: <class 'TypeError'> occured when doing scheduled job bili_watch.
[2024-03-19 16:38:08,214 b站动态监视器] ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\QQ-Bot\HoshinoBot_Blue\hoshino\service.py", line 350, in wrapper
    ret = await func()
  File "D:\QQ-Bot\HoshinoBot_Blue\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 72, in bili_watch
    rst, dylist = await dymgr.get_update()
  File "D:\QQ-Bot\HoshinoBot_Blue\hoshino\modules\bili-notice-hoshino\dymgr.py", line 299, in get_update
    for card in dylist["data"]["cards"]:
TypeError: 'NoneType' object is not iterable
```

**Comment by kushidou** [comment]
应该是B站更改了动态和视频API返回的信息，目前有多个解析错误产生。

**Comment by kendajiwaimai** [comment]
今天又出现了😂

**Comment by kushidou** [comment]
插件最近的更新更换了获取动态列表的API接口，该问题已经解决。
