### ISSUE TITLE
Python3.9.x 版本下插件加载失败~

### ISSUE THREAD

**Issue by DaiShengSheng** [kushidou/bili-notice-hoshino#41]
`2024-06-25 16:09:41.079 | INFO     | hoshino.modules.bili-notice-hoshino.dymgr:<module>:197 - Load up list success: 0
[2024-06-25 16:09:41,098 nonebot] ERROR: Failed to import "hoshino.modules.bili-notice-hoshino.bili_notice_hoshino", error: call_action() takes 2 positional arguments but 3 were given
[2024-06-25 16:09:41,105 nonebot] ERROR: call_action() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Mirai-yoshinoV2\xcwbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 65, in <module>
    async def startup():
TypeError: call_action() takes 2 positional arguments but 3 were given`

应该是和Python版本有关，按照https://github.com/kushidou/bili-notice-hoshino/issues/29 中操作能够成功加载插件，但是无法关注新账号，问问在不更改Python版本的情况下有无解决方案

**Comment by kushidou** [comment]
我自己就在使用python3.9，在api大规模风控之前都是正常加载，并且风控之后所测试的代码都还没同步到git上。

因为工作原因很久没有推进测试和修复bug，所以有可能是Hoshino更新导致的加载问题。

出问题的这一行，是在插件启动时调用代码更新身份验证参数，在禁用启动后，身份验证出现问题，b站拒绝了查询up主信息的请求。
