### ISSUE TITLE
插件出现一堆报错无法使用

### ISSUE THREAD

**Issue by CYDXDianXian** [kushidou/bili-notice-hoshino#8]
系统：windows server 2016
环境：python3.8.10
错误日志如下：
```
[2022-06-29 10:04:18,423 nonebot] ERROR: Failed to import and load "hoshino.modules.bili-notice-hoshino.bili_notice_hoshino", error: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
[2022-06-29 10:04:18,424 nonebot] ERROR: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 8, in <module>
    from . import dymgr
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 5, in <module>
    from .res import drawCard
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 7, in <module>
    from .getImg import get_ico, get_Image, round_mask
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\getImg.py", line 7, in <module>
    import cairosvg as svg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
[2022-06-29 10:04:18,439 nonebot] ERROR: Failed to import and load "hoshino.modules.bili-notice-hoshino.bili_notice_test", error: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
[2022-06-29 10:04:18,440 nonebot] ERROR: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\bili_notice_test.py", line 9, in <module>
    from .res import drawCard
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 7, in <module>
    from .getImg import get_ico, get_Image, round_mask
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\getImg.py", line 7, in <module>
    import cairosvg as svg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
[2022-06-29 10:04:18,455 nonebot] ERROR: Failed to import and load "hoshino.modules.bili-notice-hoshino.dymgr", error: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
[2022-06-29 10:04:18,456 nonebot] ERROR: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 5, in <module>
    from .res import drawCard
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 7, in <module>
    from .getImg import get_ico, get_Image, round_mask
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\getImg.py", line 7, in <module>
    import cairosvg as svg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```
依赖已全部安装成功，检查许久不知道错误具体原因何在，麻烦作者大大帮忙看看，谢谢！
安装依赖的终端记录：
```
PS C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino> pip install -r requirements.txt
Requirement already satisfied: requests==2.27.1 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 2)) (2.27.1)
Requirement already satisfied: CairoSVG in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 3)) (2.5.2)
Requirement already satisfied: urwid==2.1.2 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 4)) (2.1.2)
Requirement already satisfied: loguru in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 5)) (0.6.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 2)) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 2)) (2.0.11)
Requirement already satisfied: idna<4,>=2.5 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 2)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 2)) (1.26.8)
Requirement already satisfied: tinycss2 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from CairoSVG->-r requirements.txt (line 3)) (1.1.1)
Requirement already satisfied: cairocffi in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from CairoSVG->-r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: defusedxml in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from CairoSVG->-r requirements.txt (line 3)) (0.7.1)
Requirement already satisfied: cssselect2 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from CairoSVG->-r requirements.txt (line 3)) (0.6.0)
Requirement already satisfied: pillow in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from CairoSVG->-r requirements.txt (line 3)) (9.1.1)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from loguru->-r requirements.txt (line 5)) (1.1.0)
Requirement already satisfied: colorama>=0.3.4 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from loguru->-r requirements.txt (line 5)) (0.4.4)
Requirement already satisfied: cffi>=1.1.0 in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from cairocffi->CairoSVG->-r requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: webencodings in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from cssselect2->CairoSVG->-r requirements.txt (line 3)) (0.5.1)
Requirement already satisfied: pycparser in c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages (from cffi>=1.1.0->cairocffi->CairoSVG->-r requirements.txt (line 3)) (2.21)
PS C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino> py -V
Python 3.8.10
PS C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino>
```

**Comment by kushidou** [comment]
问题应该和#6 一样，缺少cairo库，参考一下[这一条](https://github.com/kushidou/bili-notice-hoshino/issues/6#issuecomment-1168850946)的方案。

我制作这个插件的时候是在Linux的环境，没有考虑到Widnows的适配，之后抽空到Windows搭建一个环境集中修复一下问题。

**Comment by CYDXDianXian** [comment]
作者大大我来了，我更新好了，但是问题依旧，并且我按照 #6 的做法，安装了gtk2-runtime-2.24.33-2021-01-30-ts-win64_2之后，问题依旧，但是报错发生变化。
没安装gtk2时的报错：
```
[2022-06-29 15:47:18,294 nonebot] ERROR: 档线更新失败。 请检查相关设置
[2022-06-29 15:47:19,285 nonebot] ERROR: Failed to import and load "hoshino.modules.bili-notice-hoshino.bili_notice_hoshino", error: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
[2022-06-29 15:47:19,285 nonebot] ERROR: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 4, in <module>
    from . import dymgr
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 5, in <module>
    from .res import drawCard
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 7, in <module>
    from .getImg import get_ico, get_Image, round_mask
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\getImg.py", line 7, in <module>
    import cairosvg as svg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
[2022-06-29 15:47:19,301 nonebot] ERROR: Failed to import and load "hoshino.modules.bili-notice-hoshino.bili_notice_test", error: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
[2022-06-29 15:47:19,301 nonebot] ERROR: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\bili_notice_test.py", line 9, in <module>
    from .res import drawCard
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 7, in <module>
    from .getImg import get_ico, get_Image, round_mask
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\getImg.py", line 7, in <module>
    import cairosvg as svg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
[2022-06-29 15:47:19,317 nonebot] ERROR: Failed to import and load "hoshino.modules.bili-notice-hoshino.dymgr", error: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
[2022-06-29 15:47:19,317 nonebot] ERROR: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 5, in <module>
    from .res import drawCard
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 7, in <module>
    from .getImg import get_ico, get_Image, round_mask
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\getImg.py", line 7, in <module>
    import cairosvg as svg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```
安装gtk2之后的报错：
```
[2022-06-29 15:55:30,971 nonebot] ERROR: Failed to import and load "hoshino.modules.bili-notice-hoshino.bili_notice_hoshino", error: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
[2022-06-29 15:55:30,971 nonebot] ERROR: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 4, in <module>
    from . import dymgr
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 49, in <module>
    up_group_info = json.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
[2022-06-29 15:55:30,986 nonebot] ERROR: Failed to import and load "hoshino.modules.bili-notice-hoshino.dymgr", error: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
[2022-06-29 15:55:30,986 nonebot] ERROR: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 49, in <module>
    up_group_info = json.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
```

**Comment by kushidou** [comment]
是否已经更新到最新的代码？[10fc9a1](https://github.com/kushidou/bili-notice-hoshino/commit/10fc9a1f8d3b2711aa6aeff11dd5a512f88d380d)

如果已经更新到最新代码后仍然有这个问题，删除`uppers/list.json`文件，重新创建一个空文件，里面放置一对空的花括号：
```json
{}
```
