### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object报错

### ISSUE THREAD

**Issue by CYDXDianXian** [kushidou/bili-notice-hoshino#9]
hoshinobot提供的log如下：
```
[2022-06-30 11:34:43,466 b站动态监视器] ERROR: <class 'TypeError'> occured when doing scheduled job bili_watch.
[2022-06-30 11:34:43,466 b站动态监视器] ERROR: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\service.py", line 349, in wrapper
    ret = await func()
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 24, in bili_watch
    rst, dylist = await dymgr.get_update()
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 162, in get_update
    dyimg, dytype = dynamic.draw(drawBox)   # 绘制动态
TypeError: cannot unpack non-iterable NoneType object
```
插件提供的log如下：
```
06-30 11:34:11 [INFO]	dymgr.get_update(154): ========== New Dynamic Card =========
06-30 11:34:11 [INFO]	dymgr.get_update(155): UP=不对了鸭(74085058), Dynamic_id=677403655108821017, Type=1, ori_type=2
06-30 11:34:12 [INFO]	drawCard.check_black_words(92): black-words: find 恰饭 0 times!
06-30 11:34:12 [INFO]	drawCard.check_black_words(92): black-words: find 广告 0 times!
06-30 11:34:12 [INFO]	drawCard.draw(112): ~~ Start to draw dynamic card pciture ~~
06-30 11:34:12 [DEBUG]	drawCard.draw(120): NO pendant around his/her face.
06-30 11:34:12 [DEBUG]	drawCard.draw(139): This is a normal persion.
06-30 11:34:12 [INFO]	drawCard.draw(141): FaceBox: 头像框=False, 头像角标=普通人; BoxSize=(72, 72)
06-30 11:34:12 [INFO]	drawCard.draw(148): Name&Time Box: nickname=不对了鸭, color=black, time="22-06-30 11:12"(1656558729);BoxSize=(562, 46)
06-30 11:34:12 [DEBUG]	drawCard.draw(154): Get comment number=0 form dynamic.desc.comment because Type=1
06-30 11:34:12 [INFO]	drawCard.draw(169): BottomBox: share=0, comment=0, like=0; BoxSize=(276, 48)
06-30 11:34:12 [INFO]	drawCard.drawRepost(252): Type = Repost
06-30 11:34:13 [DEBUG]	drawCard.image(705): ImageBox: num of pics = 9
06-30 11:34:13 [ERROR]	dymgr.get_update(162): An error has been caught in function 'get_update', process 'MainProcess' (105272), thread 'MainThread' (40412):
Traceback (most recent call last):
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\dymgr.py", line 162, in get_update
    dyimg, dytype = dynamic.draw(drawBox)   # 绘制动态
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 177, in draw
    bodyimg = self.drawRepost(self.card, box)
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 265, in drawRepost
    img_ori = self.drawImage(content["origin"], box, is_rep=True)
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 295, in drawImage
    img = box.image(content=text, ex=self.extra, pics=pics, pic_count=pic_count, is_reposted=is_rep)
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 707, in image
    text_img = self.text(content,ex, is_reposted)
  File "C:\Users\Administrator\qqbot\HoshinoBot\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 607, in text
    imgl.paste(emo,((point+1), 1),emo)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 1629, in paste
    self.im.paste(im, box, mask.im)
TypeError: integer argument expected, got float
```

**Comment by kushidou** [comment]
绘制文字部分时对空格的处理出了问题，导致int的地方传入了float出错。

**Comment by CYDXDianXian** [comment]
感谢老师！
